rsyslog: not available on musl
With musl C library, we get following error when building rsyslog:

  imfile.c: In function 'in_setupFileWatchStatic':
  imfile.c:1614:28: error: 'GLOB_BRACE' undeclared (first use in this function)
        GLOB_MARK|GLOB_NOSORT|GLOB_BRACE, NULL, &files);
                              ^
flag GLOB_BRACE is not available on musl. Since package uses it
unconditionally, we mark it not available for musl.

Fixes:
  http://autobuild.buildroot.net/results/6d4/6d480bb1e1466809d8ff119f6b35bb91df00785c/

Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>