ipmitool: add patch to fix missing stddef include
Needed for wchar_t. Fixes build error:

imbapi.h:140:9: error: unknown type name 'wchar_t'
 typedef wchar_t      WCHAR;

Fixes:
http://autobuild.buildroot.net/results/9e9/9e99aa8aebf68667b8c054b64e49de6dd73dd53d/
http://autobuild.buildroot.net/results/496/49637fcab9cd8e6278257158574fd7574f97bc30/
http://autobuild.buildroot.net/results/6a3/6a37f69ac40d60a1735afe5974cabec3ca5de41f/

Upstream status: Pending
https://sourceforge.net/p/ipmitool/mailman/message/35022779/

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>