package/net-tools: bump version to fix musl build
git head includes this commit
http://sourceforge.net/p/net-tools/code/ci/c35607eae8243851dd80a0181554f3a0e9e50aa8/

Due to the gettext problems the package-specific build errors were not
yet found by the autobuilders:

slattach.c:85:11: error: ‘B50’ undeclared here (not in a function)
   { "50", B50 }, { "75", B75   },
(and many more)

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>