setools: depends on host-flex
setools needs host-flex in order to generate some source files during
build time, otherwise it will fail with an error like this one:

error: policy_scan.c: No such file or directory

Issue reported here as a race condition problem, but it turned out that
it the actual problem was the lack of host-flex:

  https://github.com/TresysTechnology/setools3/issues/5#issuecomment-144048612

Fixes:

  http://autobuild.buildroot.net/results/dad/dad9d79c10722b203536540141a6defc79937e4e/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>