fbterm: fix musl compile
- add missing include, fixes:

  fbio.cpp:33:8: error: ‘fd_set’ does not name a type
   static fd_set fds;

  improxy.cpp:439:3: error: ‘fd_set’ was not declared in this scope

- add missing WAIT_ANY define, fixes:

  fbterm.cpp: In member function ‘void FbTerm::processSignal(u32)’:
  fbterm.cpp:212:22: error: ‘WAIT_ANY’ was not declared in this scope
      s32 pid = waitpid(WAIT_ANY, 0, WNOHANG);

Fixes:
http://autobuild.buildroot.net/results/ab2/ab2334700b44bac233994b76f2acf1795f0

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>