at: uses fork(), so requires MMU
Fixes the following problem:

atd.o: In function `run_file':
atd.c:(.text+0x35c): undefined reference to `fork'
atd.c:(.text+0x75c): undefined reference to `fork'
daemon.o: In function `daemon_setup':
daemon.c:(.text+0x4bc): undefined reference to `fork'
collect2: ld returned 1 exit status
make[1]: *** [atd] Error 1
make[1]: Leaving directory `/home/test/test/output/build/at-3.1.12'
make: *** [/home/test/test/output/build/at-3.1.12/.stamp_built] Error 2

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>