ne10: bump version to 1.0.0
Switch to github helper while at it.

Depend on BR2_ARM_FPU_NEON || BR2_ARM_FPU_NEON_VFPV4 so that the toolchain
wrapper will add -mfpu=neon, and avoid the following error:

.../include/arm_neon.h:32:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h

Note that this error doesn't show in the build-end.log referenced below
because of the log lines limit.

Fixes:
http://autobuild.buildroot.net/results/a2c/a2ca3fe245e410a738f4b10631a1414696a0edea/

Signed-off-by: Baruch Siach <baruch@tkos.co.il>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>