package/enlightenment: fix build issue without libuuid
Since enlightenment 0.20 uuid.h is always included in e_pixmap.c but
libuuid is checked at configure time only when wayland support is
enabled.

Include uuid.h must guarded by HAVE_WAYLAND.

Fixes:
  CC       src/bin/src_bin_enlightenment-e_pixmap.o
src/bin/e_pixmap.c:16:18: fatal error: uuid.h: No such file or directory

Signed-off-by: Romain Naour <romain.naour@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>