crda: fix build with GCC 6
Building crda with GCC 6 fails because of all compiler warnings are treated as
errors. Disable the compiler option '-Werror':

keys-gcrypt.c:94:32: error: ‘keys’ defined but not used [-Werror=unused-const-variable=]
 static const struct key_params keys[] = {
                                ^~~~
cc1: all warnings being treated as errors

Add a patch to drop '-Werror' from CFLAGS.

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>