xterm: depends on MMU
Fixes http://sysmic.org/~jezz/results/53a729c3:

button.o: In function `_executeCommand':
./button.c:(.text+0x21be): undefined reference to `_fork'
main.o: In function `_get_pty':
./main.c:(.text+0xab0): undefined reference to `_getpt'
main.o: In function `_spawnXTerm':
./main.c:(.text+0x1030): undefined reference to `_fork'
misc.o: In function `_creat_as':
./misc.c:(.text+0x3a56): undefined reference to `_fork'
print.o: In function `_charToPrinter':
./print.c:(.text+0x1ee): undefined reference to `_fork'

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>