gvfs: Depend on libgcrypt if it is selected
gvfs can make optional use of libgcrypt so it needs to depend on
it if it is selected. It's also necessary to set the
ac_cv_path_LIBGCRYPT_CONFIG variable to a known value in order
to prevent the AM_PATH_LIBGCRYPT macro from searching the host
paths for the libgcrypt-config script.

Fixes the following build problem when libgcrypt is installed on the
host system but the package is not selected in buildroot:

gvfsbackendafpbrowse.c:31:20: fatal error: gcrypt.h: No such file or directory

Signed-off-by: Markos Chandras <markos.chandras@imgtec.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>