aiccu: fix undefined reference to clock_* functions
Since glibc 2.17 the clock_* suite functions are available directly in
the main C library. For previous versions we still need -lrt to link.

Upstream is aware of this problem.

Fixes:
   http://autobuild.buildroot.net/results/c11/c1182b00f9d968e587acba15af4af905b92227f5/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>